### ISSUE TITLE
Add voice command to activate VoiceGPT

### ISSUE THREAD

**Issue by Good-Vibes-Chat-N-Chew-UK** [WSTxda/Plugin-VoiceGPT#26]
Please add the ability to activate VoiceGPT using a voice command.

The voice command used to activate VoiceGPT should be "Hey ChatGPT".

**Comment by richaardvark** [comment]
I just want to provide some background here about voice activation for voice assistants on Android 13... 

Prior to Android version 13 Google allowed third-party voice assistant applications to be able to use the microphone for wake word activation. However, Google being evil as they are decided to remove this capability when they released Android version 13. They claim this was for security reasons but I am 99% certain it is because they don't want people using voice assistants other than Google Assistant. I'm sure it might still be possible to somehow implement a wake word activation feature however it's not likely that it will be very battery efficient as the application will have to always be open and active and constantly accessing the microphone to listen in the background for any utterances of the wake word. If you can pull this off it would be great but personally I don't think it's doable due to Google's terrible limitations.

**Comment by Good-Vibes-Chat-N-Chew-UK** [comment]
😡 WHY GOOGLE WHY!!! 😡

**Comment by richaardvark** [comment]
> 😡 WHY GOOGLE WHY!!! 😡

Tell me about it. It made me so mad when they made this change. I'm disabled (I have narcolepsy which basically means sometimes I randomly fall asleep in random places in my house... like even halfway up the staircase lol) and so with my last Android phone I paid a lot more money to purchase a model that supported "Alexa built-in" which meant that my OnePlus phone had a special/extra added chip made by Qualcomm included in its design that allowed it to efficiently handle battery / power management in the background while always being able to listen for the wake word of whatever default voice assistant was set on the phone. I used Amazon Alexa instead of Google Assistant as my default voice assistant and this way if I randomly fell asleep somewhere in my home and injured myself I would have Alexa on my body or nearby at least if it wasn't near an Echo Dot and could call someone for help (this actually saved my life on one occasion where I almost drowned in the bathtub after I fell asleep in the shower and slammed my face into the shower handles / bathtub water spout and gave myself a concussion and passed out in the standing water at the bottom of the bathtub). But then Google was evil and took away the ability for third-party/non-system applications to access the microphone for wake word activation 🤬🤬🤬
